### ISSUE TITLE
Syntax conflict with SkQuery

### ISSUE THREAD

**Issue by ThePumpkin5822** [ShaneBeee/SkRecipe#5]
I've recently run into an issue where SkQuery is taking priority over [syntax ](https://skripthub.net/docs/?id=3894)for adding a custom recipe. I was wondering if syntax specific to SkRecipe could be added in so it doesn't conflict anymore. Would be appreciated, thanks.

**Comment by ShaneBeee** [comment]
Not possible since this plugin has `with id %string%` at the end of the syntaxes.

**Comment by ThePumpkin5822** [comment]
Not even towards the beginning of it? For example 

`register [new|skrecipe] (shaped|shapeless) recipe for %itemtype% (using|with ingredients) %itemtypes% with id %string% [in group %string%]`

**Comment by ShaneBeee** [comment]
Are you getting an error from it?

**Comment by ThePumpkin5822** [comment]
The syntax from SkRecipe works fine, from SkQuery, it's completely broken. Since SkQuery takes priority, I can't use the things I need from there and SkRecipe.

**Comment by ShaneBeee** [comment]
Im not sure what to tell ya. The 2 syntaxes are different and theres nothing I can do to fix that, since they aren't the same.

**Comment by ThePumpkin5822** [comment]
Looks like I messed up, my bad
